// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC86qa3jh2uw14HnEE--QwY_WS4Y3UJiqI',
    appId: '1:191769047655:web:de0222e178164cfc159ac2',
    messagingSenderId: '191769047655',
    projectId: 'paytabs-d905a',
    authDomain: 'paytabs-d905a.firebaseapp.com',
    storageBucket: 'paytabs-d905a.firebasestorage.app',
    measurementId: 'G-Y19505T7KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDTlARtwcueA6gnreNXp7FAjUfgnaZ_68',
    appId: '1:191769047655:android:2ce2303754cb2d1c159ac2',
    messagingSenderId: '191769047655',
    projectId: 'paytabs-d905a',
    storageBucket: 'paytabs-d905a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACxfY4WR97Zmer-x33H9XAR3WhahXdTg8',
    appId: '1:191769047655:ios:69b32da8445e409c159ac2',
    messagingSenderId: '191769047655',
    projectId: 'paytabs-d905a',
    storageBucket: 'paytabs-d905a.firebasestorage.app',
    iosBundleId: 'com.example.paytabsTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACxfY4WR97Zmer-x33H9XAR3WhahXdTg8',
    appId: '1:191769047655:ios:69b32da8445e409c159ac2',
    messagingSenderId: '191769047655',
    projectId: 'paytabs-d905a',
    storageBucket: 'paytabs-d905a.firebasestorage.app',
    iosBundleId: 'com.example.paytabsTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC86qa3jh2uw14HnEE--QwY_WS4Y3UJiqI',
    appId: '1:191769047655:web:c3f3f57957730a15159ac2',
    messagingSenderId: '191769047655',
    projectId: 'paytabs-d905a',
    authDomain: 'paytabs-d905a.firebaseapp.com',
    storageBucket: 'paytabs-d905a.firebasestorage.app',
    measurementId: 'G-5SMYGDKPJQ',
  );
}
